#!/usr/bin/env ruby
require 'uri'
available_files = Dir.glob("**/*.md")
linked_files = []
available_files.each do |file|
	next if file[0] == '_'
	pages = File.read(file).scan(/\(\/wiki\/(\S+)\.html\)/)
	pages.each do |page|
		linked_files << "#{page[0]}.md"
	end
end
available_files.each do |file|
	next if file[0] == '_'
	next if linked_files.include?(file)
	puts "ORPHANED PAGE: #{file}"
end
