#!/usr/bin/env ruby
require 'uri'
available_files = Dir.glob("**/*.md")
available_files.each do |file|
	pages = File.read(file).scan(/\(\/wiki\/(\S+)\.html\)/)
	pages.each do |page|
		path = "#{page[0]}.md"
		next if File.exists?(path)
		puts "MISSING PAGE: #{path} (linked from #{file})"
	end
end
